name=ThingBoard Boilerplate
version=0.1.0
author=Hartog de Mik
maintainer=Hartog de Mik <hartog.de.mik@gmail.com>
sentence=Provides a boilerplate for ThingBoard projects.
sentence=Provides a boilerplate for ThingBoard projects, giving the user the option to create and capture their own telemetry data, whilst hiding the hassle of sending it to Thing Board. Used the HTTPS api.
category=Tooling
url=https://github.com/hdemik/thingboard-boilerplate
license=MIT
architectures=esp32
includes=thingBoard.h
depends=ArduinoJson